#nginx
nginx:
	image: centos:latest
  volumes:
    - "{directry}:/usr/share/nginx/html"
  volumes:
    - "docker/nginx/logs:/Users/yume_yu/docker/nginx/log"
  ports:
    - "80:80"

#mariadb
mariadb:
	image: centos:latest

#adminer
adminer:
	image: centos:latest
  ports:
    - "8080:8080"

#python
python:
  image: centos:latest

#LDAP
ldap:
  image: centos:latest
