#nginx
nginx:
  image: nginx:latest
  volumes:
    - "{directry}:/usr/share/nginx/html"
  volumes:
    - "nginx/logs:/Users/yume_yu/docker/nginx/log"
  ports:
    - "80:80"

#mariadb
mariadb:
  image: mariadb

#serverside
serverside:
  image: centos:latest

